# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('HostIP', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='IP\u5730\u5740')),
                ('HostUser', models.CharField(default='', max_length=20, verbose_name='\u7cfb\u7edf\u8d26\u53f7')),
                ('HostPass', models.CharField(default='', max_length=100, verbose_name='\u7cfb\u7edf\u5bc6\u7801')),
                ('DBUser', models.CharField(max_length=20, verbose_name='DB\u8d26\u53f7')),
                ('DBPass', models.CharField(max_length=100, verbose_name='DB\u5bc6\u7801')),
                ('DBComment', models.CharField(max_length=200, verbose_name='DB\u5f52\u5c5e\u4e1a\u52a1')),
                ('DBMaster1', models.CharField(default='', max_length=200, verbose_name='\u4e3b\u6570\u636e\u5e931')),
                ('DBMaster2', models.CharField(default='', max_length=200, verbose_name='\u4e3b\u6570\u636e\u5e932')),
                ('DBSlave1', models.CharField(default='', max_length=200, verbose_name='\u5907\u6570\u636e\u5e931')),
                ('DBSlave2', models.CharField(default='', max_length=200, verbose_name='\u5907\u6570\u636e\u5e932')),
                ('DBSlave3', models.CharField(default='', max_length=200, verbose_name='\u5907\u6570\u636e\u5e933')),
                ('DBSlave4', models.CharField(default='', max_length=200, verbose_name='\u5907\u6570\u636e\u5e934')),
                ('CraeteTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('UpdateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a\u4fe1\u606f',
                'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f',
            },
        ),
    ]
