# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-21 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0008_auto_20180721_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='ImportLevel',
            field=models.CharField(default='\u975e\u5e38\u91cd\u8981', max_length=200, verbose_name='\u91cd\u8981\u7ea7\u522b'),
        ),
    ]
