# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-21 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0009_hostinfo_importlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='DBMaster1',
            field=models.CharField(max_length=200, null=True, verbose_name='\u4e3b\u6570\u636e\u5e931'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBMaster2',
            field=models.CharField(default=' ', max_length=200, null=True, verbose_name='\u4e3b\u6570\u636e\u5e932'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave1',
            field=models.CharField(default=' ', max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e931'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave2',
            field=models.CharField(default=' ', max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e932'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave3',
            field=models.CharField(default=' ', max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e933'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave4',
            field=models.CharField(default=' ', max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e934'),
        ),
    ]
