# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0011_auto_20180721_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='ManagerIp2',
            field=models.CharField(default='', max_length=20, verbose_name='\u7ba1\u7406\u5730\u5740'),
        ),
    ]
