# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0012_hostinfo_managerip2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='ManagerIp2',
            new_name='ManagerIp',
        ),
    ]
