# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0013_auto_20180723_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='ManagerIp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7ba1\u7406\u5730\u5740'),
        ),
    ]
