# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0014_auto_20180723_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='VirtualIp1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u865a\u62dfIP1'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='VirtualIp2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u865a\u62dfIP2'),
        ),
    ]
