# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0015_auto_20180723_1412'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hostinfo',
            table='HostInfo',
        ),
    ]
