# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0017_auto_20180723_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='Company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6240\u5c5e\u516c\u53f8'),
        ),
    ]
