# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0018_hostinfo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='MashineModel',
            field=models.CharField(blank=True, choices=[('1', 'Dell R630'), ('2', 'Dell R930'), ('3', 'Hp GEN9')], max_length=20, verbose_name='\u670d\u52a1\u5668\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBMaster2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e3b\u6570\u636e\u5e932'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e931'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e932'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e933'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='DBSlave4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6570\u636e\u5e934'),
        ),
    ]
