# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagement', '0019_auto_20180723_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='MemerySize',
            field=models.IntegerField(blank=True, choices=[('64', '64GB'), ('128', '128GB'), ('256', '236GB'), ('512', '512GB')], max_length=11, null=True, verbose_name='\u670d\u52a1\u5668\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='MashineModel',
            field=models.CharField(blank=True, choices=[('1', 'Dell R630'), ('2', 'Dell R930'), ('3', 'Hp GEN9')], max_length=20, null=True, verbose_name='\u670d\u52a1\u5668\u578b\u53f7'),
        ),
    ]
